### Регистрация нового пользователя
POST http://localhost:3001/api/auth/register
Content-Type: application/json

{
  "email": "danechkasuffer@mail.ru",
  "username": "admin123",
  "password": "mySecurePassword123"
}

### Вход пользователя (Логин)
POST http://localhost:3001/api/auth/login
Content-Type: application/json

{
  "email": "danechkasuffer@mail.ru",
  "password": "mySecurePassword123"
}